// =========================================================================== 
// Project: ConAnimSys 
// 
// Tutorial link:
// http://web.archive.org/web/20010306082236/http://www.sleepwalkertc.com/members/blitz/native/nativetut.html
//
// Description: 
// This is the header file for the CASConAnimEvent.uc class. 
// ===========================================================================

#include "Engine.h" 
#include "Core.h"

// The ConAnimSysClasses header file is automatically generated by the ucc 
// compiler. 
#include "ConAnimSysClasses.h"
