/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef CONANIMSYS_API
#define CONANIMSYS_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern CONANIMSYS_API FName CONANIMSYS_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class CONANIMSYS_API UCASConEventAnimation : public UConEvent
{
public:
    class AActor* eventOwner;
    FStringNoInit eventOwnerName;
    BYTE playMode;
    INT playLength;
    FName Sequence;
    BITFIELD bFinishAnim:1 GCC_PACK(4);
    BITFIELD bLoopAnim:1;
    DECLARE_CLASS(UCASConEventAnimation,UConEvent,0)
    NO_DEFAULT_CONSTRUCTOR(UCASConEventAnimation)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
